/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package choquedeplanetas;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author jcoq2
 */
public class ChoquePlanetas extends javax.swing.JFrame {

    /**
     * Creates new form ChoquePlanetas
     */
    
    ArrayList<Planeta> listaPlanetas = new ArrayList();
    ArrayList<Cientifico> listaCientificos = new ArrayList();

    public ChoquePlanetas() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarCientificosComboBox();
        defaultPlanetas();
        loadCientificos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Planetas = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolPlanetas = new javax.swing.JTree();
        publicosCB = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cientificosCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nombreCientifico = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jMenuItem1.setText("Planeta 1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Planetas.add(jMenuItem1);

        jMenuItem2.setText("Planeta 2");
        Planetas.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        arbolPlanetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolPlanetasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arbolPlanetas);

        publicosCB.setText("Publicos");
        publicosCB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                publicosCBStateChanged(evt);
            }
        });

        jLabel1.setText("Cientificos");

        cientificosCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cientificosCBItemStateChanged(evt);
            }
        });

        jLabel2.setText("Nombre");

        jButton1.setText("Aniadir Cientifico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Colisionar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publicosCB))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(jLabel1)
                            .addComponent(cientificosCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(nombreCientifico)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cientificosCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombreCientifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publicosCB)
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 if (nombreCientifico.getText().isEmpty()){
        }else{
            String nombre = nombreCientifico.getText();
            Cientifico cientifico = new Cientifico(nombre);
            listaCientificos.add(cientifico);
            JOptionPane.showMessageDialog(null, "Cientifico Creado");
            nombreCientifico.setText(null);
            actualizarCientificosComboBox();
            cientificoGuardado();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void arbolPlanetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolPlanetasMouseClicked

        if (evt.isMetaDown()) {
            Planetas.show(evt.getComponent(), evt.getX(), evt.getY());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_arbolPlanetasMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void publicosCBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_publicosCBStateChanged

      if(publicosCB.isSelected()){
          setTreeVisible();
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_publicosCBStateChanged

    private void cientificosCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cientificosCBItemStateChanged

        
        if(evt.getStateChange() == 2){
            planetasDescubiertosCientificos();
        }
        if(publicosCB.isSelected()){
            publicosCB.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cientificosCBItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoquePlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoquePlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoquePlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoquePlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoquePlanetas().setVisible(true);
            }
        });
    }

    public void defaultPlanetas() {
        PlanetaTerrestre mercurio = new PlanetaTerrestre("Mercurio", 13000, 5000, 400, 300);
        listaPlanetas.add(mercurio);
        PlanetaTerrestre venus = new PlanetaTerrestre("Venus", 15000, 100000, 640, 260);
        listaPlanetas.add(venus);
        PlanetaTerrestre tierra = new PlanetaTerrestre("Tierra", 17000, 140000, 760, 570);
        listaPlanetas.add(tierra);
        PlanetaTerrestre marte = new PlanetaTerrestre("Marte", 12000, 90000, 360, 360);
        listaPlanetas.add(marte);
        PlanetaGaseoso jupiter = new PlanetaGaseoso("Jupiter", 40000, 400000, 340, 310);
        listaPlanetas.add(jupiter);
        PlanetaGaseoso saturno = new PlanetaGaseoso("Saturno", 30000, 300000, 560, 450);
        listaPlanetas.add(saturno);
        PlanetaGaseoso urano = new PlanetaGaseoso("Urano", 20000, 200000, 670, 690);
        listaPlanetas.add(urano);
        PlanetaGaseoso neptuno = new PlanetaGaseoso("Neptuno", 20000, 200000, 840, 900);
        listaPlanetas.add(neptuno);

    }
    
     public void planetasDescubiertosCientificos(){
        try{
            Cientifico cientifico = (Cientifico) cientificosCB.getSelectedItem();

            DefaultTreeModel arbolModelo = (DefaultTreeModel)arbolPlanetas.getModel();
            DefaultMutableTreeNode root = new DefaultMutableTreeNode("Planetas");
            root.removeAllChildren();
            for (Planeta planeta : cientifico.getPlanetas()){
                DefaultMutableTreeNode hojaPlaneta = new DefaultMutableTreeNode(planeta);
                root.add(hojaPlaneta);
            }

            arbolModelo.setRoot(root);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    //actualizacion del comboBox
    public void actualizarCientificosComboBox(){
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)cientificosCB.getModel();
        modelo.removeAllElements();
        for (Cientifico c : listaCientificos)
            modelo.addElement(c);
    }
    
     private void loadCientificos(){
        try{
            ObjectInputStream os = new ObjectInputStream(new FileInputStream("./Cientificos"));
            Cientifico cientifico;
            while( (cientifico = (Cientifico)os.readObject()) != null )
                listaCientificos.add(cientifico);
        }catch(IOException | ClassNotFoundException e){
            System.out.println(e);
        }
    }
     
     
      public void setTreeVisible(){
        DefaultTreeModel modelo = (DefaultTreeModel)arbolPlanetas.getModel();
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Planetas");
        for (Planeta planeta : listaPlanetas){
            DefaultMutableTreeNode hijoPlaneta = new DefaultMutableTreeNode(planeta);
            root.add(hijoPlaneta);
        }
        modelo.setRoot(root);
    }
       private void cientificoGuardado(){
        try{
            ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream("./Cientificos"));
            for (Cientifico cientifico : listaCientificos)
                os.writeObject(cientifico);
        }catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Planetas;
    private javax.swing.JTree arbolPlanetas;
    private javax.swing.JComboBox<String> cientificosCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nombreCientifico;
    private javax.swing.JCheckBox publicosCB;
    // End of variables declaration//GEN-END:variables
Planeta planeta1;
Planeta planeta2;
HiloColision hiloColision;
}
